# Generated by Django 5.2.3 on 2025-07-02 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_api_id', models.CharField(max_length=50, unique=True, verbose_name='TourAPI ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='경도')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('opening_hours', models.CharField(blank=True, max_length=200, verbose_name='운영시간')),
                ('region_code', models.CharField(blank=True, max_length=20, verbose_name='지역 코드')),
                ('region_name', models.CharField(blank=True, max_length=100, verbose_name='지역 이름')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='이미지 URL')),
                ('tour_api_category_codes', models.JSONField(blank=True, default=list, verbose_name='TourAPI 카테고리 코드들')),
                ('popularity_score', models.IntegerField(default=0, verbose_name='인기도 점수')),
                ('is_idol_spot', models.BooleanField(default=False, verbose_name='아이돌 성지 여부')),
                ('idol_name', models.CharField(blank=True, max_length=100, verbose_name='관련 아이돌 이름')),
                ('idol_group', models.CharField(blank=True, max_length=100, verbose_name='관련 아이돌 그룹')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 동기화 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '관광지',
                'verbose_name_plural': '관광지들',
                'db_table': 'place',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ko', '한국어'), ('en', 'English'), ('ja', '日本語'), ('zh', '中文')], max_length=5, verbose_name='언어')),
                ('name', models.CharField(max_length=200, verbose_name='관광지명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='places.place', verbose_name='관광지')),
            ],
            options={
                'verbose_name': '관광지 번역',
                'verbose_name_plural': '관광지 번역들',
                'db_table': 'place_translation',
                'ordering': ['place_id', 'lang'],
                'unique_together': {('place', 'lang')},
            },
        ),
    ]
