# Generated by Django 5.2.3 on 2025-06-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations =[

    ]
