# Generated by Django 5.2.3 on 2025-07-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='tour_api_id',
        ),
        migrations.AddField(
            model_name='place',
            name='content_id',
            field=models.CharField(default='temp_content_id', max_length=50, unique=True, verbose_name='TourAPI Content ID'),
            preserve_default=False,
        ),
    ]
