# Generated by Django 5.2.3 on 2025-07-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetranslation',
            name='lang',
            field=models.CharField(choices=[('ko', '한국어'), ('en', 'English'), ('jp', '日本語'), ('cn', '中文')], max_length=5, verbose_name='언어 코드'),
        ),
    ]
