# Generated by Django 5.2.3 on 2025-07-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_place_tour_api_id_place_content_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='idol_group',
        ),
        migrations.RemoveField(
            model_name='place',
            name='idol_name',
        ),
        migrations.RemoveField(
            model_name='place',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='place',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='place',
            name='is_idol_spot',
        ),
        migrations.RemoveField(
            model_name='place',
            name='popularity_score',
        ),
        migrations.RemoveField(
            model_name='place',
            name='region_code',
        ),
        migrations.RemoveField(
            model_name='place',
            name='region_name',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tour_api_category_codes',
        ),
        migrations.AddField(
            model_name='place',
            name='category_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='카테고리 ID'),
        ),
        migrations.AddField(
            model_name='place',
            name='region_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='지역 ID'),
        ),
        migrations.AddField(
            model_name='place',
            name='sub_category_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='서브 카테고리 ID'),
        ),
        migrations.AddField(
            model_name='place',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='place',
            name='content_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='컨텐트 ID'),
        ),
        migrations.DeleteModel(
            name='PlaceTranslation',
        ),
    ]
