# Generated by Django 5.2.3 on 2025-07-21 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_placetranslation_lang'),
        ('regions', '0004_alter_subregiontranslation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='region_code',
        ),
        migrations.RemoveField(
            model_name='place',
            name='region_id',
        ),
        migrations.AddField(
            model_name='place',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='regions.region', verbose_name='지역'),
        ),
        migrations.AddField(
            model_name='place',
            name='sub_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='regions.subregion', verbose_name='지역구'),
        ),
    ]
