# Generated by Django 5.2.3 on 2025-07-04 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_place_idol_group_remove_place_idol_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ko', '한국어'), ('en', 'English'), ('ja', '日本語'), ('zh', '中文')], max_length=5, verbose_name='언어 코드')),
                ('name', models.CharField(max_length=200, verbose_name='관광지명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='places.place', verbose_name='관광지')),
            ],
            options={
                'verbose_name': '관광지 번역',
                'verbose_name_plural': '관광지 번역들',
                'db_table': 'place_translation',
                'ordering': ['place_id', 'lang'],
                'unique_together': {('place', 'lang')},
            },
        ),
    ]
