# Generated by Django 5.2.3 on 2025-07-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_place_region_code_remove_place_region_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetranslation',
            name='tour_api_content_id',
            field=models.CharField(blank=True, help_text='해당 언어의 투어API content ID (외부 API 호출용)', max_length=50, verbose_name='투어API 컨텐츠ID'),
        ),
    ]
