# Generated by Django 5.2.3 on 2025-06-29 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('places', '0003_placeen'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=200, null=True)),
                ('region_code', models.CharField(blank=True, max_length=20, null=True)),
                ('region_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('is_idol_spot', models.BooleanField(default=False)),
                ('idol_name', models.CharField(blank=True, max_length=100, null=True)),
                ('idol_group', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.subcategory')),
            ],
            options={
                'verbose_name': '관광지(중국어)',
                'verbose_name_plural': '관광지들(중국어)',
            },
        ),
        migrations.CreateModel(
            name='PlaceJP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=200, null=True)),
                ('region_code', models.CharField(blank=True, max_length=20, null=True)),
                ('region_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('is_idol_spot', models.BooleanField(default=False)),
                ('idol_name', models.CharField(blank=True, max_length=100, null=True)),
                ('idol_group', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.subcategory')),
            ],
            options={
                'verbose_name': '관광지(일본어)',
                'verbose_name_plural': '관광지들(일본어)',
            },
        ),
    ]
