# Generated by Django 5.2.3 on 2025-07-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_placetranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='place',
            name='view_count',
        ),
        migrations.AddField(
            model_name='place',
            name='favorite_count',
            field=models.IntegerField(default=0, verbose_name='즐겨찾기 수'),
        ),
        migrations.AddField(
            model_name='place',
            name='link_url',
            field=models.URLField(blank=True, verbose_name='공식 사이트 URL'),
        ),
        migrations.AddField(
            model_name='place',
            name='region_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='지역 코드'),
        ),
        migrations.AddField(
            model_name='place',
            name='use_time',
            field=models.CharField(blank=True, max_length=200, verbose_name='이용시간'),
        ),
    ]
