# Generated by Django 5.2.3 on 2025-07-27 17:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_placetranslation_tour_api_content_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='관광지의 위치 좌표 (경도, 위도 순서)', null=True, srid=4326, verbose_name='위치'),
        ),
    ]
