# Generated by Django 5.2.3 on 2025-07-30 05:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_remove_place_latitude_remove_place_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placetranslation',
            name='tour_api_content_id',
        ),
        migrations.AlterField(
            model_name='place',
            name='content_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='컨텐트 ID'),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Point(경도, 위도) 형식으로 저장', null=True, srid=4326, verbose_name='위치 좌표'),
        ),
    ]
