# Generated by Django 5.2.3 on 2025-07-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_placetranslation_tour_api_content_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetranslation',
            name='tour_api_content_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='투어API 컨텐츠 ID'),
        ),
    ]
