# Generated by Django 5.2.3 on 2025-07-31 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('places', '0007_placetranslation_tour_api_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='place',
            name='sub_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory', verbose_name='서브 카테고리'),
        ),
    ]
