# Generated by Django 5.2.3 on 2025-08-02 09:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_category_id_alter_place_sub_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='sub_category_id',
            new_name='sub_category',
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='위치 좌표'),
        ),
    ]
