# Generated by Django 5.2.3 on 2025-08-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_rename_category_id_place_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=10, verbose_name='지역 코드')),
                ('language', models.CharField(choices=[('ko', '한국어'), ('en', 'English'), ('jp', '日本語'), ('cn', '中文')], max_length=5, verbose_name='언어')),
                ('last_page', models.IntegerField(default=0, verbose_name='마지막 처리 페이지')),
                ('last_sync_date', models.DateTimeField(auto_now=True, verbose_name='마지막 동기화')),
                ('total_collected', models.IntegerField(default=0, verbose_name='총 수집 개수')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '동기화 진행 상태',
                'db_table': 'sync_progress',
                'ordering': ['area_code', 'language'],
                'unique_together': {('area_code', 'language')},
            },
        ),
    ]
