# Generated by Django 5.2.3 on 2025-08-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_rename_category_id_place_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='대표 이미지 URL'),
        ),
    ]
