# Generated by Django 5.2.3 on 2025-08-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_place_image_url'),
        ('places', '0010_syncprogress'),
    ]

    operations = [
    ]
