# Generated by Django 5.2.3 on 2025-08-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_merge_0010_place_image_url_0010_syncprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='전화번호'),
        ),
    ]
