# Generated by Django 5.2.3 on 2025-08-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_place_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoritePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='사용자 ID')),
                ('place_id', models.BigIntegerField(verbose_name='관광지 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '사용자 즐겨찾기 관광지',
                'verbose_name_plural': '사용자 즐겨찾기 관광지들',
                'db_table': 'user_favorite_place',
                'unique_together': {('user_id', 'place_id')},
            },
        ),
    ]
