# Generated by Django 5.2.3 on 2025-10-13 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_place_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_kpop_spot',
            field=models.BooleanField(default=False, verbose_name='K-POP 명소 여부'),
        ),
        migrations.CreateModel(
            name='IdolVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idol_name', models.CharField(max_length=100, verbose_name='아이돌 이름')),
                ('idol_group', models.CharField(blank=True, max_length=100, verbose_name='그룹명')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='방문 날짜')),
                ('source_url', models.URLField(blank=True, verbose_name='출처 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idol_visits', to='places.place', verbose_name='방문 장소')),
            ],
            options={
                'verbose_name': '아이돌 방문 기록',
                'verbose_name_plural': '아이돌 방문 기록들',
                'db_table': 'idol_visit',
                'ordering': ['-created_at'],
                'unique_together': {('place', 'idol_name')},
            },
        ),
        migrations.CreateModel(
            name='IdolVisitTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ko', '한국어'), ('en', 'English'), ('jp', '日本語'), ('cn', '中文')], max_length=5, verbose_name='언어 코드')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('idol_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='places.idolvisit', verbose_name='아이돌 방문 기록')),
            ],
            options={
                'verbose_name': '아이돌 방문 기록 번역',
                'verbose_name_plural': '아이돌 방문 기록 번역들',
                'db_table': 'idol_visit_translation',
                'ordering': ['idol_visit_id', 'lang'],
                'unique_together': {('idol_visit', 'lang')},
            },
        ),
    ]
