# Generated by Django 5.2.3 on 2025-07-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_type',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('kakao', 'Kakao'), ('naver', 'Naver')], default='email', max_length=20),
        ),
    ]
