# Generated by Django 5.2.3 on 2025-09-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_login_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_calendar_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_calendar_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_calendar_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
