# Generated by Django 5.2.3 on 2025-08-28 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='사용자 ID')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '여행 계획',
                'verbose_name_plural': '여행 계획들',
                'db_table': 'travel_plan',
            },
        ),
        migrations.CreateModel(
            name='PlanPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.BigIntegerField(verbose_name='관광지 ID')),
                ('visit_date', models.DateField(verbose_name='방문일')),
                ('visit_time', models.TimeField(blank=True, null=True, verbose_name='방문 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_places', to='plans.travelplan', verbose_name='여행 계획')),
            ],
            options={
                'verbose_name': '계획 관광지',
                'verbose_name_plural': '계획 관광지들',
                'db_table': 'plan_place',
            },
        ),
        migrations.CreateModel(
            name='TravelPlanTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ko', 'Korean'), ('en', 'English'), ('jp', 'Japanese'), ('cn', 'Chinese')], max_length=5, verbose_name='언어 코드')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='plans.travelplan', verbose_name='여행 계획')),
            ],
            options={
                'verbose_name': '여행 계획 번역',
                'verbose_name_plural': '여행 계획 번역들',
                'db_table': 'travel_plan_translation',
                'unique_together': {('travel_plan', 'lang')},
            },
        ),
    ]
