# Generated by Django 5.2.3 on 2025-08-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='subregion_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='서브지역 ID'),
        ),
        migrations.AddField(
            model_name='travelplantranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='여행 설명'),
        ),
        migrations.AddField(
            model_name='travelplantranslation',
            name='destination',
            field=models.CharField(blank=True, max_length=200, verbose_name='여행지'),
        ),
    ]
