# Generated by Django 5.2.3 on 2025-09-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_travelplan_subregion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='시작일'),
        ),
    ]
