# Generated by Django 5.2.3 on 2025-09-04 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_travelplan_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplantranslation',
            name='destination',
        ),
    ]
