# Generated by Django 5.2.3 on 2025-09-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_remove_travelplantranslation_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planplace',
            name='place_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='관광지 ID'),
        ),
    ]
