# Generated by Django 5.2.3 on 2025-09-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_planplace_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planplace',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='방문일'),
        ),
    ]
