# Generated by Django 5.2.3 on 2025-09-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_alter_planplace_visit_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='planplace',
            index=models.Index(fields=['travel_plan'], name='idx_plan_place_travel_plan'),
        ),
        migrations.AddIndex(
            model_name='travelplan',
            index=models.Index(fields=['user_id'], name='idx_travel_plan_user_id'),
        ),
        migrations.AddIndex(
            model_name='travelplan',
            index=models.Index(fields=['user_id', 'end_date'], name='idx_travel_plan_user_end'),
        ),
    ]
