# Generated by Django 5.2.3 on 2025-10-24 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idolrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '아이돌 신청', 'verbose_name_plural': '아이돌 신청'},
        ),
        migrations.AlterField(
            model_name='idolrequest',
            name='additional_notes',
            field=models.TextField(blank=True, null=True, verbose_name='비고/하고 싶은 말'),
        ),
        migrations.AlterField(
            model_name='idolrequest',
            name='admin_memo',
            field=models.TextField(blank=True, null=True, verbose_name='관리자 메모'),
        ),
        migrations.AlterField(
            model_name='idolrequest',
            name='agency',
            field=models.CharField(blank=True, max_length=100, verbose_name='소속사'),
        ),
        migrations.AlterField(
            model_name='idolrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='신청일'),
        ),
        migrations.AlterField(
            model_name='idolrequest',
            name='idol_name',
            field=models.CharField(max_length=100, verbose_name='아이돌/그룹 이름'),
        ),
        migrations.AlterField(
            model_name='idolrequest',
            name='related_info',
            field=models.TextField(blank=True, null=True, verbose_name='관련정보'),
        ),
        migrations.AlterField(
            model_name='idolrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='idolrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idol_requests', to=settings.AUTH_USER_MODEL, verbose_name='신청자'),
        ),
    ]
