# Generated by Django 5.2.3 on 2025-08-27 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0012_alter_place_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='places.place', verbose_name='즐겨찾는 장소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_places', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '즐겨찾는 장소',
                'verbose_name_plural': '즐겨찾는 장소들',
                'db_table': 'favorite_place',
                'indexes': [models.Index(fields=['user'], name='favorite_pl_user_id_0da130_idx'), models.Index(fields=['place'], name='favorite_pl_place_i_093d1e_idx'), models.Index(fields=['created_at'], name='favorite_pl_created_e5bd4f_idx')],
                'unique_together': {('user', 'place')},
            },
        ),
    ]
