# Generated by Django 5.2.3 on 2025-08-29 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        ('regions', '0006_regiontranslation_features_alter_subregion_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSubRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('sub_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='regions.subregion', verbose_name='즐겨찾는 지역구')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_subregions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '즐겨찾는 지역구',
                'verbose_name_plural': '즐겨찾는 지역구들',
                'db_table': 'favorite_subregion',
                'indexes': [models.Index(fields=['user'], name='favorite_su_user_id_f6f02e_idx'), models.Index(fields=['sub_region'], name='favorite_su_sub_reg_77dd1d_idx'), models.Index(fields=['created_at'], name='favorite_su_created_a4346a_idx')],
                'unique_together': {('user', 'sub_region')},
            },
        ),
    ]
