# Generated by Django 5.2.3 on 2025-06-30 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10, verbose_name='언어 코드')),
                ('name', models.CharField(max_length=50, verbose_name='번역된 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='categories.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '카테고리 번역',
                'verbose_name_plural': '카테고리 번역들',
                'db_table': 'category_translation',
                'unique_together': {('category', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='SubCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10, verbose_name='언어 코드')),
                ('name', models.CharField(max_length=50, verbose_name='번역된 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='categories.subcategory', verbose_name='서브카테고리')),
            ],
            options={
                'verbose_name': '서브카테고리 번역',
                'verbose_name_plural': '서브카테고리 번역들',
                'db_table': 'subcategory_translation',
                'unique_together': {('sub_category', 'lang')},
            },
        ),
    ]
