# Generated by Django 5.2.3 on 2025-07-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categorytranslation_subcategorytranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '카테고리', 'verbose_name_plural': '카테고리'},
        ),
        migrations.AlterModelOptions(
            name='categorytranslation',
            options={'verbose_name': '카테고리 번역', 'verbose_name_plural': '카테고리 번역'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': '서브 카테고리', 'verbose_name_plural': '서브 카테고리'},
        ),
        migrations.AlterModelOptions(
            name='subcategorytranslation',
            options={'verbose_name': '서브카테고리 번역', 'verbose_name_plural': '서브카테고리 번역'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_cn',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_jp',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ko',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_cn',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_jp',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_ko',
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='lang',
            field=models.CharField(help_text='ko, en, jp, cn', max_length=10, verbose_name='언어 코드'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='번역된 이름'),
        ),
        migrations.AlterField(
            model_name='subcategorytranslation',
            name='lang',
            field=models.CharField(help_text='ko, en, jp, cn', max_length=10, verbose_name='언어 코드'),
        ),
        migrations.AlterField(
            model_name='subcategorytranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='번역된 이름'),
        ),
    ]
