"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")
TOUR_API_SERVICE_KEY = os.getenv("TOUR_API_SERVICE_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1", cast=lambda v: [s.strip() for s in v.split(',')])

# 환경변수에서 읽도록 설정
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SECURE_BROWSER_XSS_FILTER = config('SECURE_BROWSER_XSS_FILTER', default=False, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",

    "rest_framework",
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    "corsheaders",
    "drf_yasg",
    "django_celery_beat",
    "storages",

    "users",
    "places",
    "plans",
    "exports",
    "categories",
    "regions",
    "preferences",
    "weather",
    "favorites",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
        "OPTIONS": {
            "sslmode": config("DB_SSL_MODE", default="require"),
        },
        # 개발 환경에서는 연결 재사용
        "CONN_MAX_AGE": 60 if DEBUG else 0,
    }
}

# Custom User Model
AUTH_USER_MODEL = "users.CustomUser"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = False

# 지원 언어 설정 (다국어 서비스용)
LANGUAGES = [
    ("ko", "한국어"),
    ("en", "English"),
    ("jp", "日本語"),
    ("cn", "中文"),
]

DEFAULT_LANG = "ko"

# 국제화 파일 경로
LOCALE_PATHS = [
    BASE_DIR / "locale",
]



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOWED_ORIGINS = [
    # 로컬 개발용
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",

    # 운영 환경용 - S3 프론트엔드
    "https://korip.me",
    "https://www.korip.me",

    # API 자체 테스트용
    "https://api.korip.me",
]

CSRF_TRUSTED_ORIGINS = [
    "https://korip.me",
    "https://www.korip.me",
    "https://api.korip.me",
    "http://localhost:9000",
    "http://127.0.0.1:9000",
]

ALLOWED_HOSTS = [
    "api.korip.me",
    "korip.me",
    "www.korip.me",
    "localhost",
    "127.0.0.1",
    "43.201.253.255",
]

CORS_ALLOW_CREDENTIALS = True

# REST Framework 설정
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [  # 튜플 대신 리스트
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    
    'JTI_CLAIM': 'jti',
    
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
    
    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT token을 "Bearer {token}" 형식으로 입력하세요'
        }
    },
    'USE_SESSION_AUTH': False,
}

# 개발 환경에서만 적용되는 설정들
if DEBUG:
    # SQL 쿼리 로깅 (개발시 유용)
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
            },
        },
        "loggers": {
            "django.db.backends": {
                "handlers": ["console"],
                "level": "INFO",  # DEBUG로 하면 너무 많이 나와서 INFO로 설정
                "propagate": False,
            },
        },
    }

    # 개발 환경용 CORS 설정 (모든 오리진 허용)
    CORS_ALLOW_ALL_ORIGINS = True

# 디버깅용 로그 설정
# if DEBUG:
#     LOGGING = {
#         "version": 1,
#         "disable_existing_loggers": False,
#         "handlers": {
#             "console": {
#                 "class": "logging.StreamHandler",
#             },
#         },
#         "root": {
#             "handlers": ["console"],
#             "level": "INFO",
#         },
#         "loggers": {
#             "django.db.backends": {
#                 "handlers": ["console"],
#                 "level": "DEBUG",
#                 "propagate": False,
#             },
#         },
#     }

# 이메일 인증시 메일 발송을 위한 Gmail SMTP 설정
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config("EMAIL_SMTP_SERVER")
EMAIL_PORT = config("EMAIL_SMTP_PORT")
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_ACCOUNT")
EMAIL_HOST_PASSWORD = config("EMAIL_PASSWORD")
DEFAULT_FROM_EMAIL = config("EMAIL_ACCOUNT")


# Django Redis 캐시 설정
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': config("REDIS_URL"),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

#  GIS 관련 설정 추가
GDAL_LIBRARY_PATH = None  # 자동 감지
GEOS_LIBRARY_PATH = None  # 자동 감지

# GIS Admin 맵 설정
GEOIP_PATH = None

# 맵 타일 서비스 설정 (선택사항)
OSM_MAP_TILE_URL = "https://tile.openstreetmap.org/{z}/{x}/{y}.png"

# cron 작업 설정
# CRONJOBS = [
#     # 매일 새벽 1시에 1000개 관광지 데이터 수집
#     ("0 1 * * *", "django.core.management.call_command", ["sync_tour_api", "--limit=1000"]),
# ]

# 기상청 API 키 (환경변수에서 로드)
WEATHER_API_KEY = config("WEATHER_API_KEY", default="")

# HTTPS 사용 여부 (운영환경: True, 개발환경: False)
USE_HTTPS = config("USE_HTTPS", default=True, cast=bool)

# 날씨 API 관련 설정
WEATHER_API_SETTINGS = {
    "API_KEY": WEATHER_API_KEY,
    "USE_HTTPS": USE_HTTPS,
    "TIMEOUT": 30,  # API 응답 대기 시간 (초)
    "RETRY_COUNT": 3,  # 재시도 횟수
    "CACHE_TIMEOUT": 300,  # 캐시 유지 시간 (5분)
}

# API 호출 제한 설정
WEATHER_API_RATE_LIMITS = {
    "REQUESTS_PER_MINUTE": 60,  # 분당 최대 요청 수
    "REQUESTS_PER_HOUR": 1000,  # 시간당 최대 요청 수
}

# Celery Configuration
CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "redis://redis:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Seoul"

# 스케줄 설정 - 2시간마다 전국 날씨 수집
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    "sync-weather-all-regions-every-2-hours": {
        "task": "weather.tasks.sync_weather_task",
        "schedule": crontab(minute=0, hour="*/2"),  # 2시간마다 정각 (0시, 2시, 4시, 6시, 8시, 10시, 12시, 14시, 16시, 18시, 20시, 22시)
        "args": (),  # 빈 튜플 = region_id=None = 전체 지역
    },
    "sync-tour-api-daily": {
        "task": "places.tasks.sync_tour_api_daily",
        "schedule": crontab(hour=3, minute=0),  # 매일 새벽 3시
        "args": (),
    },
    "sync-tour-api-weekly": {
        "task": "places.tasks.sync_tour_api_weekly",
        "schedule": crontab(hour=1, minute=0, day_of_week=0),  # 매주 일요일 새벽 1시
        "args": (),
    },
}

# Google Calendar API 설정
GOOGLE_OAUTH2_CLIENT_ID = config("GOOGLE_OAUTH2_CLIENT_ID")
GOOGLE_OAUTH2_CLIENT_SECRET = config("GOOGLE_OAUTH2_CLIENT_SECRET")

# OAuth 리디렉션 URL (개발용)
GOOGLE_OAUTH2_REDIRECT_URI = "http://localhost:9000/api/exports/auth/google/callback/"

# 운영 환경에서는 이걸로 변경
# GOOGLE_OAUTH2_REDIRECT_URI = "https://korip.me/api/exports/auth/google/callback/"

# Google Calendar API 스코프 (권한)
GOOGLE_CALENDAR_SCOPES = [
    "https://www.googleapis.com/auth/calendar",  # 캘린더 읽기/쓰기
    "https://www.googleapis.com/auth/userinfo.email",  # 사용자 이메일
]

# S3 설정
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = "ap-northeast-2"
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

# 명시적 설정 추가
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_DEFAULT_ACL = None
AWS_S3_FILE_OVERWRITE = False

# 스토리지 백엔드 설정
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

# MEDIA 설정
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"
