# Generated by Django 5.2.3 on 2025-07-16 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_count', models.IntegerField(default=0, help_text='이 지역구의 관광지 개수', verbose_name='관광지 수')),
                ('favorite_count', models.IntegerField(default=0, help_text='이 지역구가 즐겨찾기된 횟수', verbose_name='즐겨찾기 수')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='날씨 API 연동용 대표 위도', max_digits=10, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='날씨 API 연동용 대표 경도', max_digits=11, null=True, verbose_name='경도')),
                ('sort_order', models.IntegerField(default=0, help_text='수동 정렬용 순서 (낮을수록 우선)', verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='regions.region', verbose_name='부모 지역')),
            ],
            options={
                'verbose_name': '서브지역',
                'verbose_name_plural': '서브지역',
                'db_table': 'subregion',
                'ordering': ['-favorite_count', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RegionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ko', '한국어'), ('en', 'English'), ('ja', '日本語'), ('zh', '中文')], max_length=5, verbose_name='언어 코드')),
                ('name', models.CharField(max_length=100, verbose_name='지역 이름')),
                ('description', models.TextField(blank=True, help_text='이 지역에 대한 간단한 설명 (예: 전통과 현대가 공존하는 도시)', verbose_name='지역 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='regions.region', verbose_name='지역')),
            ],
            options={
                'verbose_name': '지역 번역',
                'verbose_name_plural': '지역 번역',
                'db_table': 'region_translation',
                'unique_together': {('region', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='SubRegionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ko', '한국어'), ('en', 'English'), ('ja', '日本語'), ('zh', '中文')], max_length=5, verbose_name='언어 코드')),
                ('name', models.CharField(max_length=100, verbose_name='서브지역 이름')),
                ('description', models.TextField(blank=True, help_text='이 지역구에 대한 간단한 설명', verbose_name='지역 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('sub_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='regions.subregion', verbose_name='서브지역')),
            ],
            options={
                'verbose_name': '서브지역 번역',
                'verbose_name_plural': '서브지역 번역',
                'db_table': 'subregion_translation',
                'unique_together': {('sub_region', 'lang')},
            },
        ),
    ]
