# Generated by Django 5.2.3 on 2025-07-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subregion',
            options={'ordering': ['-favorite_count', 'translations__name'], 'verbose_name': '지역구', 'verbose_name_plural': '지역구'},
        ),
        migrations.AlterModelOptions(
            name='subregiontranslation',
            options={'verbose_name': '지역구 번역', 'verbose_name_plural': '서브지역 번역'},
        ),
        migrations.RemoveField(
            model_name='subregion',
            name='place_count',
        ),
        migrations.RemoveField(
            model_name='subregion',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='subregiontranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='지역구 이름'),
        ),
        migrations.AlterField(
            model_name='subregiontranslation',
            name='sub_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='regions.subregion', verbose_name='지역구'),
        ),
    ]
