# Generated by Django 5.2.3 on 2025-07-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_alter_subregion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subregiontranslation',
            name='features',
            field=models.TextField(blank=True, help_text='이 지역구의 특징 설명 (예: 트레디한 쇼핑몰과 고급 레스토랑)', verbose_name='특징'),
        ),
    ]
