# Generated by Django 5.2.3 on 2025-07-27 18:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_alter_subregiontranslation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subregion',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='subregion',
            name='longitude',
        ),
        migrations.AddField(
            model_name='subregion',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='날씨 API 연동용 대표 위치 (경도, 위도)', null=True, srid=4326, verbose_name='위치'),
        ),
    ]
