# Generated by Django 5.2.3 on 2025-08-09 15:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_remove_subregion_latitude_remove_subregion_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiontranslation',
            name='features',
            field=models.TextField(blank=True, help_text='이 지역의 특징 설명 (예: K-POP과 전통 문화의 중심지, 다양한 쇼핑몰과 맛집)', verbose_name='특징'),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='대표 위치 (경도, 위도)', null=True, srid=4326, verbose_name='위치'),
        ),
    ]
