# Generated by Django 5.2.3 on 2025-09-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0006_regiontranslation_features_alter_subregion_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ImageField(blank=True, help_text='지역을 대표하는 이미지 파일', null=True, upload_to='regions/', verbose_name='지역 이미지'),
        ),
    ]
