# Generated by Django 5.2.3 on 2025-08-09 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0005_remove_subregion_latitude_remove_subregion_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='현재 시점의 기온', verbose_name='현재 기온(℃)')),
                ('min_temperature', models.FloatField(blank=True, help_text='하루 중 최저 기온', null=True, verbose_name='최저 기온(℃)')),
                ('max_temperature', models.FloatField(blank=True, help_text='하루 중 최고 기온', null=True, verbose_name='최고 기온(℃)')),
                ('humidity', models.IntegerField(help_text='현재 습도 (0-100%)', verbose_name='습도(%)')),
                ('precipitation', models.IntegerField(help_text='강수 확률 (0-100%)', verbose_name='강수확률(%)')),
                ('sky_code', models.CharField(help_text='1:맑음, 3:구름많음, 4:흐림', max_length=10, verbose_name='하늘상태')),
                ('precipitation_type', models.CharField(help_text='0:없음, 1:비, 2:비/눈, 3:눈, 5:빗방울, 6:빗방울눈날림, 7:눈날림', max_length=10, verbose_name='강수형태')),
                ('wind_speed', models.FloatField(blank=True, help_text='바람의 속도', null=True, verbose_name='풍속(m/s)')),
                ('wind_direction', models.IntegerField(blank=True, help_text='바람이 불어오는 방향 (0-360도)', null=True, verbose_name='풍향(도)')),
                ('forecast_time', models.DateTimeField(help_text='이 날씨 정보가 적용되는 시간', verbose_name='예보 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('region', models.ForeignKey(help_text='날씨 정보를 조회할 지역', on_delete=django.db.models.deletion.CASCADE, to='regions.region', verbose_name='지역')),
            ],
            options={
                'verbose_name': '날씨',
                'verbose_name_plural': '날씨 정보',
                'db_table': 'weather',
                'ordering': ['-forecast_time'],
                'unique_together': {('region', 'forecast_time')},
            },
        ),
    ]
