# Generated by Django 5.2.3 on 2025-08-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='feels_like_temperature',
            field=models.FloatField(blank=True, help_text='실제로 느끼는 온도', null=True, verbose_name='체감온도(℃)'),
        ),
        migrations.AddField(
            model_name='weather',
            name='pm10',
            field=models.FloatField(blank=True, help_text='PM10 농도', null=True, verbose_name='초미세먼지(μg/m³)'),
        ),
        migrations.AddField(
            model_name='weather',
            name='pm25',
            field=models.FloatField(blank=True, help_text='PM2.5 농도', null=True, verbose_name='미세먼지(μg/m³)'),
        ),
        migrations.AddField(
            model_name='weather',
            name='sunrise_time',
            field=models.TimeField(blank=True, help_text='해가 뜨는 시간', null=True, verbose_name='일출 시간'),
        ),
        migrations.AddField(
            model_name='weather',
            name='sunset_time',
            field=models.TimeField(blank=True, help_text='해가 지는 시간', null=True, verbose_name='일몰 시간'),
        ),
        migrations.AddField(
            model_name='weather',
            name='uv_index',
            field=models.IntegerField(blank=True, help_text='0-11 (0:낮음, 3-5:보통, 6-7:높음, 8-10:매우높음, 11+:위험)', null=True, verbose_name='자외선 지수'),
        ),
    ]
