# Generated by Django 5.2.3 on 2025-08-12 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0006_regiontranslation_features_alter_subregion_location'),
        ('weather', '0002_weather_feels_like_temperature_weather_pm10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(help_text='대기질 측정소 이름', max_length=100, verbose_name='측정소명')),
                ('measurement_date', models.CharField(help_text='측정 일시 (YYYY-MM-DD HH:MM)', max_length=20, verbose_name='측정 일시')),
                ('pm10_value', models.IntegerField(blank=True, help_text='미세먼지 농도', null=True, verbose_name='PM10 농도(μg/m³)')),
                ('pm25_value', models.IntegerField(blank=True, help_text='초미세먼지 농도', null=True, verbose_name='PM2.5 농도(μg/m³)')),
                ('pm10_grade', models.CharField(blank=True, help_text='미세먼지 등급 (좋음, 보통, 나쁨, 매우나쁨)', max_length=10, null=True, verbose_name='PM10 등급')),
                ('pm25_grade', models.CharField(blank=True, help_text='초미세먼지 등급 (좋음, 보통, 나쁨, 매우나쁨)', max_length=10, null=True, verbose_name='PM2.5 등급')),
                ('so2_value', models.FloatField(blank=True, help_text='SO2 농도', null=True, verbose_name='아황산가스(ppm)')),
                ('co_value', models.FloatField(blank=True, help_text='CO 농도', null=True, verbose_name='일산화탄소(ppm)')),
                ('o3_value', models.FloatField(blank=True, help_text='O3 농도', null=True, verbose_name='오존(ppm)')),
                ('no2_value', models.FloatField(blank=True, help_text='NO2 농도', null=True, verbose_name='이산화질소(ppm)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '대기질 데이터',
                'verbose_name_plural': '대기질 데이터',
                'db_table': 'air_quality_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(help_text='날씨 조회 지역 이름', max_length=100, verbose_name='지역명')),
                ('latitude', models.FloatField(help_text='위도 좌표', verbose_name='위도')),
                ('longitude', models.FloatField(help_text='경도 좌표', verbose_name='경도')),
                ('current_temperature', models.FloatField(help_text='현재 시점의 기온', verbose_name='현재 기온(℃)')),
                ('humidity', models.IntegerField(help_text='현재 습도 (0-100%)', verbose_name='습도(%)')),
                ('pm25_value', models.IntegerField(blank=True, help_text='초미세먼지 농도', null=True, verbose_name='PM2.5(μg/m³)')),
                ('pm10_value', models.IntegerField(blank=True, help_text='미세먼지 농도', null=True, verbose_name='PM10(μg/m³)')),
                ('uv_index', models.IntegerField(blank=True, help_text='0-11 (0:낮음, 3-5:보통, 6-7:높음, 8-10:매우높음, 11+:위험)', null=True, verbose_name='자외선 지수')),
                ('sunrise_time', models.CharField(blank=True, help_text='일출 시간 (HH:MM)', max_length=10, null=True, verbose_name='일출 시간')),
                ('sunset_time', models.CharField(blank=True, help_text='일몰 시간 (HH:MM)', max_length=10, null=True, verbose_name='일몰 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '날씨 데이터',
                'verbose_name_plural': '날씨 데이터',
                'db_table': 'weather_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='region',
            field=models.ForeignKey(blank=True, help_text='날씨 정보를 조회할 지역', null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.region', verbose_name='지역'),
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(help_text='예보 지역 이름', max_length=100, verbose_name='지역명')),
                ('nx', models.IntegerField(help_text='기상청 격자 X 좌표', verbose_name='격자 X좌표')),
                ('ny', models.IntegerField(help_text='기상청 격자 Y 좌표', verbose_name='격자 Y좌표')),
                ('forecast_date', models.CharField(help_text='예보 날짜 (YYYYMMDD)', max_length=8, verbose_name='예보 날짜')),
                ('forecast_time', models.CharField(help_text='예보 시간 (HHMM)', max_length=4, verbose_name='예보 시간')),
                ('temperature', models.FloatField(blank=True, help_text='예보 기온', null=True, verbose_name='기온(℃)')),
                ('humidity', models.IntegerField(blank=True, help_text='예보 습도', null=True, verbose_name='습도(%)')),
                ('precipitation_probability', models.IntegerField(blank=True, help_text='강수 확률 (0-100%)', null=True, verbose_name='강수확률(%)')),
                ('sky_condition', models.CharField(blank=True, help_text='1:맑음, 3:구름많음, 4:흐림', max_length=10, null=True, verbose_name='하늘상태')),
                ('precipitation_type', models.CharField(blank=True, help_text='0:없음, 1:비, 2:비/눈, 3:눈', max_length=10, null=True, verbose_name='강수형태')),
                ('wind_speed', models.FloatField(blank=True, help_text='바람 속도', null=True, verbose_name='풍속(m/s)')),
                ('wind_direction', models.IntegerField(blank=True, help_text='바람 방향 (0-360도)', null=True, verbose_name='풍향(도)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '날씨 예보',
                'verbose_name_plural': '날씨 예보',
                'db_table': 'weather_forecast',
                'ordering': ['forecast_date', 'forecast_time'],
                'unique_together': {('nx', 'ny', 'forecast_date', 'forecast_time')},
            },
        ),
    ]
