# Generated by Django 5.2.3 on 2025-08-13 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0006_regiontranslation_features_alter_subregion_location'),
        ('weather', '0003_airqualitydata_weatherdata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherData',
        ),
        migrations.RemoveField(
            model_name='weatherforecast',
            name='location_name',
        ),
        migrations.AddField(
            model_name='airqualitydata',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='regions.region', verbose_name='지역'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airqualitydata',
            name='sub_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subregion', verbose_name='지역구'),
        ),
        migrations.AddField(
            model_name='weather',
            name='sub_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subregion', verbose_name='지역구'),
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='regions.region', verbose_name='지역'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='sub_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subregion', verbose_name='지역구'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='co_value',
            field=models.FloatField(blank=True, null=True, verbose_name='일산화탄소(ppm)'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='measurement_date',
            field=models.CharField(max_length=20, verbose_name='측정 일시'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='no2_value',
            field=models.FloatField(blank=True, null=True, verbose_name='이산화질소(ppm)'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='o3_value',
            field=models.FloatField(blank=True, null=True, verbose_name='오존(ppm)'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='pm10_grade',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PM10 등급'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='pm10_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='PM10 농도(μg/m³)'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='pm25_grade',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PM2.5 등급'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='pm25_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='PM2.5 농도(μg/m³)'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='so2_value',
            field=models.FloatField(blank=True, null=True, verbose_name='아황산가스(ppm)'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='station_name',
            field=models.CharField(max_length=100, verbose_name='측정소명'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='feels_like_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='체감온도(℃)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='forecast_time',
            field=models.DateTimeField(verbose_name='예보 시간'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.IntegerField(verbose_name='습도(%)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='max_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='최고 기온(℃)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='min_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='최저 기온(℃)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pm10',
            field=models.FloatField(blank=True, null=True, verbose_name='PM10(μg/m³)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pm25',
            field=models.FloatField(blank=True, null=True, verbose_name='PM2.5(μg/m³)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='precipitation',
            field=models.IntegerField(verbose_name='강수확률(%)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='precipitation_type',
            field=models.CharField(max_length=10, verbose_name='강수형태'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='regions.region', verbose_name='지역'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='sky_code',
            field=models.CharField(max_length=10, verbose_name='하늘상태'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='sunrise_time',
            field=models.TimeField(blank=True, null=True, verbose_name='일출 시간'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='sunset_time',
            field=models.TimeField(blank=True, null=True, verbose_name='일몰 시간'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(verbose_name='현재 기온(℃)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='uv_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='자외선 지수'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_direction',
            field=models.IntegerField(blank=True, null=True, verbose_name='풍향(도)'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='풍속(m/s)'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='forecast_date',
            field=models.CharField(max_length=8, verbose_name='예보 날짜'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='forecast_time',
            field=models.CharField(max_length=4, verbose_name='예보 시간'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='humidity',
            field=models.IntegerField(blank=True, null=True, verbose_name='습도(%)'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='nx',
            field=models.IntegerField(verbose_name='격자 X좌표'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='ny',
            field=models.IntegerField(verbose_name='격자 Y좌표'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='precipitation_probability',
            field=models.IntegerField(blank=True, null=True, verbose_name='강수확률(%)'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='precipitation_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='강수형태'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='sky_condition',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='하늘상태'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='기온(℃)'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='wind_direction',
            field=models.IntegerField(blank=True, null=True, verbose_name='풍향(도)'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='풍속(m/s)'),
        ),
    ]
