# Generated by Django 5.2.3 on 2025-08-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0006_regiontranslation_features_alter_subregion_location'),
        ('weather', '0004_delete_weatherdata_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('region', 'sub_region', 'forecast_time')},
        ),
    ]
