# Generated by Django 5.2.3 on 2025-08-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_weather_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='morning_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='아침 기온(6시 기준)'),
        ),
        migrations.AddField(
            model_name='weather',
            name='temperature_change_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='아침 대비 기온 변화 텍스트'),
        ),
    ]
